[package]
name = "hello_gpu"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
anyhow = "1.0.87"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
metal = "0.29.0"
